###

GET http://localhost:8000

###

POST http://localhost:8000/user
Content-Type: application/json

{
    
    "full_name": "Samuel Mwangi",
    "email": "samuel202mwangi@gmail.com",
    "contact_phone": "0794204071",
    "address": "45 Gituamba",
    "role":"admin",
    "created_at": "2024-07-02",
    "updated_at": "2024-07-02"
}

###
GET http://localhost:8000/users

###
GET http://localhost:8000/location/1

###
POST http://localhost:8000/register
Content-Type: application/json

{

    "full_name": "David Macharia",
    "user_name":"Davy",
    "password":"@davy*##",
    "email": "kdavidmacharia8485@gmail.com",
    "contact_phone": "0742545572",
    "address": "0400 Kitale"
}

###
POST http://localhost:8000/login
Content-Type: application/json

{
    "email":"samuel202mwangi@gmail.com",
    "password":"@sammy*##"
}


###
Get http://localhost:8000/vehiclespec/5
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo1LCJ1c2VyX25hbWUiOiJzaW1tb04iLCJyb2xlIjoidXNlciIsImV4cCI6MTcyMDk1ODA1MX0.tAk2xEA0lbgBPyaClKv2UNmB1l-hj4Ba-QUAkmnhRJM


###
Get http://localhost:8000/vehicles


###
POST http://localhost:8000/vehiclespec
Content-Type: application/json

{

  "manufacturer": "Honda",
  "model": "CBR600RR",
  "year": 2022,
  "status": "Available",
  "price": 12000,
  "price_type": "USD",
  "location": "Los Angeles, CA",
  "time": "2023-08-15",
  "transmission": "Manual",
  "mileage": "500 miles",
  "fuel_type": "Gasoline",
  "type": "motorcycle",
  "engine_capacity": "599cc",
  "seating_capacity": 2,
  "color": "Red",
  "features": "ABS, Adjustable Suspension"
}

###
PUT  http://localhost:8000/user-status/5
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjozLCJ1c2VyX25hbWUiOiJTYW1teSIsInJvbGUiOiJhZG1pbiIsImV4cCI6MTcyMTMxODg5M30.89wo0PFhE0ggbSsadfUOk9mUr9y2yuSts2UK00Mn7ss

{
  "status": "disabled"
}

###
Get http://localhost:8000/tickets


###
POST http://localhost:8000/fleet
Content-Type: application/json

{

  "vehiclespec_id": 29,
  "acquisition_date": "8/22/2017",
  "depreciation_rate":0.03,
  "current_value":2100000,
  "maintenance_cost":8000,
  "status": "Good"
}

###
POST https://car-server-busc.onrender.com/checkout-session
Content-Type: application/json

{  
  "bookingId":10,
  "amount":10000
}

###
POST http://localhost:8000/forgot-password
Content-Type: application/json

{  
  "email":"antonygatitu327@gmail.com"
}

